name: CI

on:
  push:
    tags:
      - "*"
    branches:
      - main
  pull_request:

jobs:
  validate-packer:
    name: Validate Packer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run 'cd packer && packer validate packer.json'
  validate-terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run 'cd terraform && terraform init && terraform validate'
  validate-nomad:
    name: Validate Nomad
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run 'nomad validate axiom.nomad'